[[PipeWireAO]]
arch = "aarch64"
git-tree-sha1 = "859dacf510d3b66a4a1ea8b8c569fce5d2ca1d7f"
libc = "glibc"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "775bfa252cdaaabbc8bfcc5d9f06bf932df0deaccc9d21be2e026f4bae72ee87"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+15/PipeWireAO.v1.7.0.aarch64-linux-gnu.tar.gz"
[[PipeWireAO]]
arch = "x86_64"
git-tree-sha1 = "1dd4d947e373d00298cb8b8441a714f541ce0743"
libc = "glibc"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "d22a8aef0df12507fe4c1adeeca2cc0c37547ed9406b31afb825c44d8b1f069e"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+15/PipeWireAO.v1.7.0.x86_64-linux-gnu.tar.gz"
[[PipeWireAO]]
arch = "x86_64"
git-tree-sha1 = "3bdd756923b623eb5c93c69f86a9e0c0e74c041b"
libc = "glibc"
march = "avx2"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "0da42c7de1e77083067d307142dcaa3ab7fd1f85abdb4408eba8e39ba0751705"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+15/PipeWireAO.v1.7.0.x86_64-linux-gnu-march+avx2.tar.gz"
[[PipeWireAO]]
arch = "x86_64"
git-tree-sha1 = "f2bdf91aaea7969cf2b35cc16b751c4df6692150"
libc = "glibc"
march = "avx512"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "927f4245be40df07ef02c0ab33dbe5d85c2f96a42a5ca9c4d12ad736c7bc65b8"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+15/PipeWireAO.v1.7.0.x86_64-linux-gnu-march+avx512.tar.gz"
[[PipeWireAO]]
arch = "x86_64"
git-tree-sha1 = "1dd4d947e373d00298cb8b8441a714f541ce0743"
libc = "glibc"
march = "x86_64"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "d22a8aef0df12507fe4c1adeeca2cc0c37547ed9406b31afb825c44d8b1f069e"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+15/PipeWireAO.v1.7.0.x86_64-linux-gnu-march+x86_64.tar.gz"
