[[PipeWireAO]]
arch = "x86_64"
git-tree-sha1 = "f19c1c9d8c613a6dd0dd772c47b5ac64774929ba"
libc = "glibc"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "17c3852bb3f41c48744d354a03bfe9d3a89c566019acc43d5efcc797356628e5"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+1/PipeWireAO.v1.7.0.x86_64-linux-gnu.tar.gz"
[[PipeWireAO]]
arch = "aarch64"
git-tree-sha1 = "149bd699d982627c054f7bb5c8d4217e40ec625b"
libc = "glibc"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "66e1dd3a497d745217a10a0151cdae6d95315fd18d5cfcf52c7238d95c6b5f98"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+8/PipeWireAO.v1.7.0.aarch64-linux-gnu.tar.gz"
[[PipeWireAO]]
arch = "x86_64"
git-tree-sha1 = "c841f7797229d7b0f3b03f6b9fa5d044844121a5"
libc = "glibc"
march = "avx2"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "355676093fe8907c3eae4c21cf6980bdca533253fb2d1da98615ef104ebef607"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+8/PipeWireAO.v1.7.0.x86_64-linux-gnu-march+avx2.tar.gz"
[[PipeWireAO]]
arch = "x86_64"
git-tree-sha1 = "402cabdf193c92b8a125746084bcf22f18e8863b"
libc = "glibc"
march = "avx512"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "22271e36334ebdbbae6e70c4f41e288fc7b8772890c066439680ed8e0a157e40"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+8/PipeWireAO.v1.7.0.x86_64-linux-gnu-march+avx512.tar.gz"
[[PipeWireAO]]
arch = "x86_64"
git-tree-sha1 = "ba6f329a912092f14e08893cc309ebe51985679c"
libc = "glibc"
march = "x86_64"
os = "linux"

    [[PipeWireAO.download]]
    sha256 = "faf2ef5ff7b4cb45906d9d40423d4b8ca8a71a816ee2f5c73add39d937581403"
    url = "https://github.com/DarrylGamroth/PipeWireAO_jll.jl/releases/download/PipeWireAO-v1.7.0+8/PipeWireAO.v1.7.0.x86_64-linux-gnu-march+x86_64.tar.gz"
