# Autogenerated wrapper script for PipeWireAO_jll for x86_64-linux-gnu-march+avx512
export libpipewire_ao, libspa_ao, libspa_support

JLLWrappers.@generate_wrapper_header("PipeWireAO")
JLLWrappers.@declare_library_product(libpipewire_ao, "libpipewire-ao-0.3.so.0")
JLLWrappers.@declare_library_product(libspa_ao, "libspa-ao.so")
JLLWrappers.@declare_library_product(libspa_support, "libspa-support.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpipewire_ao,
        "lib/libpipewire-ao-0.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspa_ao,
        "lib/spa-ao-0.2/libspa-ao.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspa_support,
        "lib/spa-ao-0.2/support/libspa-support.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
    ENV["PIPEWIREAO_SPA_PLUGIN_DIR"] = get(ENV, "PIPEWIREAO_SPA_PLUGIN_DIR", joinpath(artifact_dir, "lib", "spa-ao-0.2"))
ENV["PIPEWIREAO_MODULE_DIR"] = get(ENV, "PIPEWIREAO_MODULE_DIR", joinpath(artifact_dir, "lib", "pipewire-ao-0.3"))
ENV["PIPEWIREAO_CONFIG_DIR"] = get(ENV, "PIPEWIREAO_CONFIG_DIR", joinpath(artifact_dir, "share", "pipewire-ao"))

end  # __init__()
